### ISSUE TITLE
Errno98 Adress already in Use

### ISSUE THREAD

**Issue by Morthi** [DarkflameUniverse/AccountManager#12]
* Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 561, in <module>
    run_app()
  File "app.py", line 557, in run_app
    app.run(host='0.0.0.0', port=5000)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 982, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use

anyone know how to fix that?

**Comment by Br3akout** [comment]
Got the same problem. It worked but only locally and it stopped working and giving OSError: [Errno 98] Address already in use
after I switched to WSL1

**Comment by bingo5387** [comment]
If you're like me an followed the YouTube guide that provides the script for setting up port forwarding before realizing WSL2 won't work, the issue is caused because WSL1 is now using the host computer's IP address and the host computer is now listening on those ports. Just run `netsh interface portproxy reset` in PowerShell to remove the port forwarding.
